# Generated by Django 5.2.8 on 2025-11-17 15:24

from django.db import migrations
from django.contrib.auth.hashers import make_password

def seed_data(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Caravan = apps.get_model('core', 'Caravan')

    # Create a guest user (for making reservations)
    guest_user, _ = User.objects.update_or_create(
        pk=1,
        defaults={
            'username': 'guestuser',
            'password': make_password('password'),
            'user_type': 'GUEST',
            'is_staff': False,
            'is_superuser': False,
        }
    )

    # Create a host user (for owning caravans)
    host_user, _ = User.objects.update_or_create(
        username='hostuser',
        defaults={
            'password': make_password('password'),
            'user_type': 'HOST',
            'is_staff': False,
            'is_superuser': False,
        }
    )

    # Create sample caravans
    Caravan.objects.get_or_create(
        host=host_user,
        name='Cozy Camper',
        defaults={
            'description': 'A small and cozy camper for two. Perfect for a weekend getaway.',
            'capacity': 2,
            'location': 'Mountain View',
            'status': 'AVAILABLE',
            'amenities': ['Kitchen', 'Shower', 'Wi-Fi'],
        }
    )
    
    Caravan.objects.get_or_create(
        host=host_user,
        name='Family Voyager',
        defaults={
            'description': 'Spacious and comfortable, this caravan is ideal for family trips.',
            'capacity': 6,
            'location': 'Beachside Park',
            'status': 'AVAILABLE',
            'amenities': ['Kitchen', 'Bunk Beds', 'TV', 'Air Conditioning'],
        }
    )

    Caravan.objects.get_or_create(
        host=host_user,
        name='Luxury Liner',
        defaults={
            'description': 'Experience the road in style with this top-of-the-line luxury caravan.',
            'capacity': 4,
            'location': 'Metropolis RV Resort',
            'status': 'MAINTENANCE',
            'amenities': ['Full Kitchen', 'King Bed', 'Satellite TV', 'Heated Floors'],
        }
    )

def unseed_data(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Caravan = apps.get_model('core', 'Caravan')
    User.objects.filter(username__in=['guestuser', 'hostuser']).delete()
    Caravan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_code=unseed_data),
    ]