# Generated by Django 5.2.7 on 2025-11-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaravanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='caravan_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('caravan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.caravan')),
            ],
        ),
    ]
