# Generated by Django 5.2.7 on 2025-11-21 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_caravan_created_at_caravan_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('caravan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='core.caravan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('caravan', 'start_date', 'end_date'), name='unique_blocked_period_for_caravan')],
            },
        ),
    ]
