# Generated by Django 5.2.7 on 2025-11-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blockedperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
